Projects:
    type: entity
    table: projects
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 200
            fixed: false
            nullable: false
        category1:
            type: integer
            unsigned: false
            nullable: false
            column: _category1
        category2:
            type: integer
            unsigned: false
            nullable: false
            column: _category2
        date:
            type: date
            nullable: false
        software:
            type: string
            length: 1000
            fixed: false
            nullable: false
        description:
            type: text
            nullable: false
        thumb:
            type: integer
            unsigned: false
            nullable: false
            column: _thumb
        cover:
            type: integer
            unsigned: false
            nullable: false
            column: _cover
        excerpt:
            type: string
            length: 1000
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
