<?php

namespace Pm\PortfolioBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ArticleController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Pm\PortfolioBundle\Controller\ArticleController();
        return $instance;
    }
}
