parameters:
#    pm_portfolio.example.class: Pm\PortfolioBundle\Example

services:
#    pm_portfolio.example:
#        class: %pm_portfolio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
